import { Figures} from './figures';
import { Grille } from './grille';




export class Scene {

  private readonly canvas: HTMLCanvasElement;
  private readonly ctx: CanvasRenderingContext2D;
  private readonly typeFigures: number = 0; // 0: losange, 1: triangle, 2: triangle rectangle, 3: hexagone, 4: octogone
  private readonly tailleFigures: number;
  private readonly figures: Figures[] = [];
  private readonly grille: Array<Array<number>> = [];
  private readonly couleurInitiale: {h: number, s: number, l: number};
  private readonly couleurFinale: {h: number, s: number, l: number};
  private nombreLignes: number = 0;
  private nombreColonnes: number = 0;
  private scrollCible : number = 0;
  private scrollActuel : number = 0;


  constructor(canvasId: string, typeFigures: number, tailleFigures: number) {
    this.canvas = document.getElementById(canvasId) as HTMLCanvasElement;
    this.ctx = this.canvas.getContext("2d")!;
    this.canvas.width = window.innerWidth;
    this.canvas.height = window.innerHeight;
    this.typeFigures = typeFigures;
    this.tailleFigures = tailleFigures;
    this.nombreColonnes = Math.ceil(this.canvas.width / (this.tailleFigures/2)) + 1; // /2
    this.nombreLignes = Math.ceil(this.canvas.height / this.tailleFigures) + 1;
    this.couleurInitiale = {h:220, s:10, l:12};
    this.couleurFinale = {h:220, s:15, l:5};// hsl -> plus sombre que la couleur finale pour un effet de révélation
    
    const grilleInstance = new Grille(this.nombreColonnes, this.nombreLignes, this.typeFigures, this.tailleFigures);
    // Synchronize figures with the ones generated by Grille
    this.figures = grilleInstance.figures;

    this.initEventListeners();

  }

  /*******************************************Gestion des événements******************************************************* */

  private initEventListeners(): void {
    window.addEventListener("scroll", () => {
      this.scrollCible = window.scrollY;
    }, { passive: true });

    window.addEventListener("resize", () => {
      this.canvas.width = window.innerWidth;
      this.canvas.height = window.innerHeight;
      this.nombreColonnes = Math.ceil(this.canvas.width / (this.largeurFigures/2)) + 1; // à modifer par une formule plus complexe ou un paramètre d'environnement
      this.nombreLignes = Math.ceil(this.canvas.height / this.hauteurFigures) + 1; // à modifer par une formule plus complexe ou un paramètre d'environnement
    });

  }

  public start(): void {
      this.loop();
  }

  private loop(): void {
    this.scrollActuel += (this.scrollCible - this.scrollActuel) * 0.1; 
    const fondEcranFacteur = Math.min(this.scrollActuel / 500, 1); // Facteur pour faire évoluer la couleur de fond en fonction du scroll
    const fondEcranCouleurL = 12-(fondEcranFacteur * 5); // Faire évoluer la luminosité du fond de 15% à 10% en fonction du scroll// Lissage du scroll
    //this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    this.ctx.fillStyle = `hsl(${this.couleurInitiale.h}, ${this.couleurInitiale.s}%, ${fondEcranCouleurL}%)`; // Couleur de fond
    this.ctx.fillRect(0, 0, this.canvas.width, this.canvas.height); // Remplir le fond
    const tempsEcoule = Math.min(this.scrollActuel / 2000, 1); // Temps écoulé en secondes
    // this.ctx.beginPath(); à remettre après test
    // this.ctx.fillStyle = COULEUR_FILL_LOSANGES; à 
    this.figures.forEach((figure) => figure.calculerProgression(this.ctx, this.scrollActuel, tempsEcoule, this.canvas.width, this.canvas.height));
    //this.ctx.fill(); à remettre après test
    requestAnimationFrame(() => this.loop()); // Continue la boucle d'animation
  }

}